### ISSUE TITLE
Ruby script broken when system http proxy is set

### ISSUE THREAD

**Issue by tddschn** [pglombardo/pwpush-alfred#4]
## log:
```
22:34:02.150] ERROR: PasswordPusher[Run Script] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "127.0.0.1:8888" (URI::InvalidURIError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/generic.rb:1542:in `find_proxy'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1109:in `proxy_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1096:in `proxy?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:936:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:605:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:528:in `post_form'
	from -e:19:in `<main>'
[22:34:02.163] PasswordPusher[Run Script] Processing complete
[22:34:02.165] PasswordPusher[Run Script] Passing output '' to Copy to Clipboard
[22:34:02.167] PasswordPusher[Run Script] Passing output '' to Open URL
[22:34:02.168] PasswordPusher[Run Script] Passing output '' to Post Notification
```

## context
macOS version: 13.4 (22F66)

I have system proxy set to localhost:8888 (yes, it's a proxy server running locally), I think this caused the error above.

## workflow version

v1.2 installed directly from alfred gallery (https://alfred.app/workflows/pglombardo/passwordpusher/)

**Comment by pglombardo** [comment]
Hi @tddschn - how do you configure that proxy in the environment?  Via environment variable?

The error is that `127.0.0.1:8888` isn't a valid URI which is technically correct.  Wherever you set that value could you try `http://127.0.0.1:8888`?

**Comment by tddschn** [comment]
I guess Alfred read macOS's system proxy settings and inject them as env vars into the workflows since I didn't set it in the shell env var, and Alfred wouldn't be able to read them there.

In macOS's settings (Network > Advanced > Proxy) I've set http & https proxies' host to 127.0.0.1, and port to 8888. The protocols are http and https respectively.

I tested this theory in Alfred by creating a `Run Script` step that runs `printenv | grep -i 'proxy'`, and the output are shown below, there's no `http://` in those env vars. I think it's an Alfred bug.


<img width="799" alt="CleanShot-2023-05-27T11-59-48@2x" src="https://github.com/pglombardo/pwpush-alfred/assets/45612704/ce05c28b-c391-4414-8542-e3efc337deb7">
<img width="683" alt="CleanShot-2023-05-27T12-01-51@2x" src="https://github.com/pglombardo/pwpush-alfred/assets/45612704/e69abe5f-a411-4184-bd11-70e7690e3b14">

**Comment by pglombardo** [comment]
That helps thanks @tddschn.  I'll see if I can test this out myself and put in a fix soon.
